[build]
  command = "node scripts/netlify-build.js"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/parametros"
  to = "/.netlify/functions/parametros"
  status = 200

[[redirects]]
  from = "/api/cotizar"
  to = "/.netlify/functions/cotizar"
  status = 200
